created_at: '2025-12-24T23:33:18.788020'
metrics:
  n_estimators_used: 2000
  n_features: 65
  n_test: 47274
  n_train: 142199
  rmse_gap: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    RDPeH/GpPcA=
  test_rmse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    j1YCVnsrAEA=
  test_spearman: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    7n6FhRwC0z8=
  test_top1_acc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JrSX0F5Cxz8=
  train_rmse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    JINe/Rq/9j8=
  train_spearman: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CeON7mxs4j8=
  train_top1_acc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    YpEy8HTr0D8=
n_features: 65
objective: regression
target: finish_time_seconds
version: mu_time_v1
